services:
  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=patient_registration
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=patient_registration
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - EMAIL_USER=<YOUR_EMAIL_USER>
      - EMAIL_PASSWORD=<YOUR_EMAIL_APP_PASSWORD>
    ports:
      - '3000:3000'
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - db

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
